src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Un compte avec cette adresse mail existe déjà.')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    /** @noinspection PhpPropertyOnlyWrittenInspection */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $user_id ;

    #[ORM\Column(length: 180, unique: true)]
    private string $email;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private string $password;

    #[ORM\Column(length: 32)]
    private string $firstName;

    #[ORM\Column(length: 32)]
    private string $lastName;

    /**
     * false is a man, true a woman
     * @var bool
     */
    #[ORM\Column]
    private bool $gender;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Adresse::class)]
    private Collection $addresses;

    #[ORM\OneToOne(targetEntity: Adresse::class)]
    #[ORM\JoinColumn(name: "default_address_id")]
    private ?Adresse $defaultAddress = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commande::class)]
    private Collection $orders;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: PanierProduit::class)]
    private Collection $cartProducts;

    public function __construct() {
        $this->orders = new ArrayCollection();
        $this->cartProducts = new ArrayCollection();
        $this->addresses = new ArrayCollection();
    }

    public function getUserId(): int {
        return $this->user_id;
    }

    public function getEmail(): string {
        return $this->email;
    }

    public function setEmail(string $email): static {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string {
        return $this->firstName." ".$this->lastName;
    }

    public function getRoles(): array {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string {
        return $this->password;
    }

    public function setPassword(string $password): static {
        $this->password = $password;

        return $this;
    }

    public function eraseCredentials(): void {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getGender(): bool {
        return $this->gender;
    }

    public function setGender(bool $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getOrders(): Collection {
        return $this->orders;
    }

    public function setOrders(Collection $orders): void
    {
        $this->orders = $orders;
    }

    public function getCartProducts(): Collection
    {
        return $this->cartProducts;
    }

    public function countCartProducts(): int {
        return count($this->cartProducts);
    }

    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function getDefaultAddress(): ?Adresse
    {
        return $this->defaultAddress;
    }

    public function setDefaultAddress(?Adresse $defaultAddress): void
    {
        $this->defaultAddress = $defaultAddress;
    }
}

src/Controller/UserPageController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Repository\AdresseRepository;
use App\Repository\CommandeRepository;
use App\Service\Snackbar\ErrorSnackbar;
use App\Service\Snackbar\SuccessSnackbar;
use App\Service\Validation\AddressValidatorService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UserPageController extends BaseController
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly AdresseRepository $adresseRepository,
        private readonly AddressValidatorService $addressValidator
    ) {}

    #[Route('/profile', name: 'user_page')]
    public function profile(): Response {
        return $this->redirectToRoute('user_informations');
    }

    #[Route('/profile/informations', name: 'user_informations')]
    public function profileInformations(Request $request): Response {
        if (!$this->userConnected) {
            return $this->redirectToRoute('login');
        }

        $session = $request->getSession();
        $snackbarType = $session->get("snackbarType");
        if (!is_null($snackbarType)) {
            $session->remove("snackbarType");
            switch ($snackbarType) {
                case "success":
                    $this->addSnackbar(new SuccessSnackbar(
                        "Confirmation",
                        "Votre mot de passe à bien été modifié."
                    ));
                    break;
                case "errorIncorrectPwd":
                    $this->addSnackbar(new ErrorSnackbar(
                        "Impossible de changer le mot de passe",
                        "Le mot de passe actuel est incorrect, veuillez réessayer."
                    ));
                    break;
                case "errorSamePwd":
                    $this->addSnackbar(new ErrorSnackbar(
                        "Impossible de changer le mot de passe",
                        "Le nouveau mot de passe est identique à l'ancien, veuillez choisir un autre mot de passe."
                    ));
                    break;
            }
        }

        return $this->render('user_page/user_informations.html.twig', [
            'identifier' => $this->user->getUserIdentifier(),
            'email' => $this->user->getEmail(),
            'firstName' => $this->user->getFirstName(),
            'lastName' => $this->user->getLastName(),
            'gender' => $this->user->getGender(),
            'nombreArticle' => $this->nombreArticle,
            'categories' => $this->categories,
            'sousCategories' => $this->subCategories,
        ]);
    }

    #[Route('/profile/addresses', name: 'user_addresses')]
    public function profileAddresses(): Response
    {
        if (!$this->userConnected) {
            return $this->redirectToRoute('login');
        }

        $addresses = $this->adresseRepository->findBy([
            'user' => $this->user->getUserId()
        ]);
        $defaultAddress = $this->user->getDefaultAddress();

        return $this->render('user_page/addresses/user_addresses.html.twig', [
            'identifier' => $this->user->getUserIdentifier(),
            'addresses' => $addresses,
            'defaultAddress' => $defaultAddress,
            'nombreArticle' => $this->nombreArticle,
            'categories' => $this->categories,
            'sousCategories' => $this->subCategories,
        ]);
    }

    #[Route('/profile/addresses/addAddress', name: 'addAddress')]
    public function addAddress(Request $request): Response
    {
        if (!$this->userConnected) {
            return $this->redirectToRoute('login');
        }

        if ($request->getMethod() == 'GET') {
            return $this->render('user_page/addresses/add_address.html.twig', [
                'identifier' => $this->user->getUserIdentifier(),
                'nombreArticle' => $this->nombreArticle,
                'categories' => $this->categories,
                'sousCategories' => $this->subCategories,
            ]);
        }


        $gender = $request->request->getString('gender');
        $firstName = $request->request->getString('firstName');
        $phoneNumber = $request->request->getString('phoneNumber');
        $lastName = $request->request->getString('lastName');
        $postalCode = $request->request->getString('postalCode');
        $city = $request->request->getString('city');
        $addressLine = $request->request->getString('address');

        $violations = $this->addressValidator->validateFields($gender,
            $firstName, $lastName, $phoneNumber,
            $addressLine, $postalCode, $city
        );
        if ($violations->count() > 0) {
            return $this->addErrorsAndRedirect($violations, 'addAddress');
        }

        $gender = (bool) $gender;

        $address = $this->adresseRepository->findOneBy([
            'user' => $this->user->getUserId(), 'gender' => $gender,
            'firstName' => $firstName, 'lastName' => $lastName,
            'phoneNumber' => $phoneNumber, 'addressLine' => $addressLine,
            'postalCode' => $postalCode, 'city' => $city
        ]);

        if (!is_null($address)) {
            $this->addSnackbar(new ErrorSnackbar(
                "Une erreur s'est produite.",
                "L'adresse existe déjà. Si vous souhaitez la modifier, allez dans la section \"Mes adresses\"."
            ));
            return $this->redirectToRoute('addAddress');
        }

        $newAddress = new Adresse(
            $this->user, $gender,
            $firstName, $lastName,
            $phoneNumber, $addressLine,
            $postalCode, $city
        );

        $this->entityManager->persist($newAddress);

        $isDefault = $request->request->getBoolean('is-default');

        if ($isDefault) {
            $this->user->setDefaultAddress($newAddress);
        }

        $this->entityManager->flush();

        $this->addSnackbar(new SuccessSnackbar(
            "Opération réussis",
            "L'adresse a été ajouté avec succès."
        ));
        return $this->redirectToRoute('user_addresses');
    }

    #[Route('/profile/addresses/editAddress', name: 'editAddress', methods: 'POST')]
    public function editAddress(Request $request): Response
    {
        if (!$this->userConnected) {
            return $this->redirectToRoute('login');
        }

        $addressId = $request->request->getInt('addressId');
        if ($addressId === 0) {
            $this->addSnackbar(new ErrorSnackbar(
                "Une erreur s'est produite.",
                "L'adresse demandée n'existe pas."
            ));
            return $this->redirectToRoute('user_addresses');
        }

        $address = $this->adresseRepository->findOneBy([
            'id' => $addressId,
            'user' => $this->user->getUserId()
        ]);

        if (is_null($address)) {
            $this->addSnackbar(new ErrorSnackbar(
                "Une erreur s'est produite.",
                "Impossible de modifier l'adresse, veuillez réessayer."
            ));
            return $this->redirectToRoute('user_addresses');
        }

        return $this->render('user_page/addresses/edit_address.html.twig', [
            'identifier' => $this->user->getUserIdentifier(),
            'adresse' => $address,
            'nombreArticle' => $this->nombreArticle,
            'categories' => $this->categories,
            'sousCategories' => $this->subCategories,
        ]);
    }

    #[Route('/profile/addresses/modifyAddress', name: 'modifyAddress', methods: 'POST')]
    public function modifyAddress(Request $request): Response {
        if (!$this->userConnected) {
            return $this->redirectToRoute('login');
        }

        $gender = $request->request->getString('gender');
        $city = $request->request->getString('city');
        $postalCode = $request->request->getString('postalCode');
        $addressLine = $request->request->getString('address');
        $phoneNumber = $request->request->getString('phoneNumber');
        $lastName = $request->request->getString('lastName');
        $firstName = $request->request->getString('firstName');

        $violations = $this->addressValidator->validateFields($gender,
            $firstName, $lastName, $phoneNumber,
            $addressLine, $postalCode, $city
        );

        if ($violations->count() > 0) {
            return $this->addErrorsAndRedirect($violations, 'editAddress');
        }

        $gender = (bool) $gender;

        $addressId = $request->request->getInt('addressId');
        if ($addressId === 0) {
            $this->addSnackbar(new ErrorSnackbar(
                "Une erreur s'est produite.",
                "La modification de l'adresse a échoué, merci de bien vouloir réessayer."
            ));
            return $this->redirectToRoute('user_addresses');
        }

        $address = $this->adresseRepository->findOneBy([
            'id' => $addressId,
            'user' => $this->user->getUserId()
        ]);

        if (is_null($address)) {
            $this->addSnackbar(new ErrorSnackbar(
                "Une erreur s'est produite.",
                "Impossible de modifier l'adresse, veuillez réessayer."
            ));
            return $this->redirectToRoute('user_addresses');
        }

        $address->setGender($gender);
        $address->setFirstName($firstName);
        $address->setLastName($lastName);
        $address->setPhoneNumber($phoneNumber);
        $address->setAddressLine($addressLine);
        $address->setPostalCode($postalCode);
        $address->setCity($city);

        $this->entityManager->flush();

        $this->addSnackbar(new SuccessSnackbar(
            "Opération réussis",

templates/user_page/user_informations.html.twig
{% extends 'user_page/user_page.html.twig' %}

{% block user_page_stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/user_page/user_informations.css') }}">
{% endblock %}


{% block user_page_content %}
<div class="section" id="details">
    <span class="section-title">Coordonnées</span>
    <div class="form-group">
        <div class="form-field">
            <label for="email">Email :</label>
            <input id="email" size="40" value="{{ email }}" autocomplete="false" disabled>
        </div>

        <div class="form-field">
            <label for="firstName">Prénom :</label>
            <input id="firstName" size="40" value="{{ firstName }}" autocomplete="false" disabled>
        </div>

        <div class="form-field">
            <label for="lastName">Nom :</label>
            <input id="lastName" size="40" value="{{ lastName }}" autocomplete="false" disabled>
        </div>

        <div class="form-field" id="gender">
            <span>Civilité :</span>
            <div id="gender-group">
                <div>
                    <label>
                        <input type="radio" class="radio-button" {{ not gender ? 'checked'}} disabled>
                        M.
                    </label>
                </div>

                <div>
                    <label>
                        <input type="radio" class="radio-button" {{ gender ? 'checked'}} disabled>
                        Mme
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section" id="change-password">
    <span class="section-title">Changer votre mot de passe</span>

    <form action="{{ path('password_change') }}" autocomplete="off" method="post">
        <div class="form-group">
            <div class="form-field">
                <label for="old-password">Ancien mot de passe :</label>
                <input type="password" name="old-password" id="old-password" size="40" required>
            </div>

            <div class="form-field">
                <label for="new-password">Nouveau mot de passe :</label>
                <input type="password" name="new-password" id="new-password" size="40" required>
            </div>
        </div>

        <button type="submit" class="white" id="change-password-button">Valider</button>
    </form>
</div>
{% endblock %}

templates/user_page/user_orders.html.twig
{% extends 'user_page/user_page.html.twig' %}

{% block user_page_stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/user_page/user_orders.css') }}">
{% endblock %}


{% block user_page_content %}
<div class="section" id="order-section">
    <span class="section-title">Vos commandes</span>

    <div id="orders">
        {% for commande in commandes|reverse %}
            <div class="order">
                <div class="order-header">
                    <div class="order-information">
                        <span>COMMANDE EFFECTUÉE LE</span>
                        <span>{{ commande.orderDate|format_datetime('long', 'none', locale='fr') }}</span>
                    </div>

                    <div class="order-information">
                        <span>LIVRAISON À</span>
                        <span>{{ not commande.gender ? 'M.' : 'Mme' }} {{ commande.firstName }} {{ commande.lastName }}</span>
                    </div>

                    <div class="order-information">
                        <span>TOTAL</span>
                        <span>{{ commande.totalPrice }} €</span>
                    </div>

                    <div class="order-information">
                        <span>N° DE COMMANDE</span>
                        <span>{{ commande.user.userId }}-{{ commande.id }}</span>
                    </div>

                    <button type="button" class="toggle-button">
                        Détail
                        <img alt="up arrow" src="{{ asset('assets/up_arrow.svg') }}" width="32" height="32">
                    </button>
                </div>
                <div class="order-content">
                        <div class="table">
                            <div class="tr">
                                <div class="th">Articles</div>
                                <div class="th">Prix</div>
                                <div class="th">Quantité</div>
                                <div class="th">Prix total</div>
                            </div>
                            {% for commandeProduit in commande.orderProducts %}
                            {% set produit, quantite = commandeProduit.product, commandeProduit.quantity %}
                                <div class="tr">
                                    <div class="td">
                                        <div class="product-title">
                                            <img alt="{{ produit.title }}" src="{{ asset('assets/Produits/' ~ produit.nomImage) }}" width="120" height="120">
                                            {{ produit.title }}
                                        </div>
                                    </div>
                                    <div class="td price gras">{{ produit.price }} €</div>
                                    <div class="td">{{ quantite }}</div>
                                    <div class="td price gras">{{ produit.price * quantite }} €</div>
                                    <div class="td buy-again">
                                        <a type="button" href="{{ '/product?' ~ {'ref': produit.title}|url_encode }}">
                                            Acheter à nouveau
                                            <img alt="buy again logo" src="{{ asset('assets/Panier3.svg') }}" width="40" height="40">
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                    </div>
                </div>
            </div>
        {% else %}
            Vous n'avez aucune commande.
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{{ asset('scripts/toggleOrder.js') }}"></script>
{% endblock %}

templates/user_page/user_page.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/user_page/user_page.css') }}">
    {% block user_page_stylesheets %}{% endblock %}
{% endblock %}

{% block header %}
    {% include asset('headers/searchHeader.html.twig') %}
{% endblock %}

{% block content %}
<div class="wrapper">
    <span class="title gras">Votre Compte</span>
    <div class="wrapper-content">
        <div class="section" id="sidebar">
            <span class="section-title">Bonjour</span>
            <span id="identifier">{{ identifier }}</span>
            <form action="{{ path('logout') }}" method="post">
                <button class="gras" type="submit" id="logout">ME DÉCONNECTER</button>
            </form>
            <div id="sidebar-sections">
                <a type="button" href="{{ path('user_informations') }}" class="sidebar-button">Mes informations</a>
                <a type="button" href="{{ path('user_addresses') }}" class="sidebar-button">Mes adresses</a>
                <a type="button" href="{{ path('user_orders') }}" class="sidebar-button">Mes commandes</a>
            </div>
        </div>

        {% block user_page_content %}{% endblock %}
    </div>
</div>
{% endblock %}

{% block footer %}
    {% include asset('footer.html.twig') %}
{% endblock %}